Repository Typiqally/epsilon, pull requests merged in 2022-06, with the labels that each got.

#9 Separating logic and cli sections
  Epsilon.Abstractions/Export/ICanvasModuleCollectionExporter.cs
  Epsilon.Canvas.Abstractions/ICanvasModuleCollectionFetcher.cs
  Epsilon.Canvas/CanvasModuleCollectionFetcher.cs
  Epsilon.Canvas/CanvasServiceCollectionExtensions.cs
  Epsilon.Canvas/Epsilon.Canvas.csproj
  Epsilon.Canvas/Service/AssignmentService.cs
  Epsilon.Canvas/Service/ModuleService.cs
  Epsilon.Canvas/Service/OutcomeService.cs
  Epsilon.Cli/Startup.cs
  Epsilon.Http.Abstractions/Epsilon.Http.Abstractions.csproj
  Epsilon.Http.Abstractions/HttpService.cs
  Epsilon.Http.Abstractions/Json/HttpClientJsonExtensions.cs
  Epsilon.Http.Abstractions/Json/HttpResponseMessageJsonExtensions.cs
  Epsilon.sln
  Epsilon/Export/CanvasModuleCollectionExporter.cs
  Epsilon/Export/CsvCanvasModuleFileExporter.cs
  Epsilon/Extensions/CoreServiceCollectionExtensions.cs
Labels: enhancement

#10 Creating Ci pipeline
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
Labels: enhancement

#12 Made a wiki and referenced this in the readme
  README.md
Labels: documentation

#15 Adding xls export type
  Epsilon.Canvas.Abstractions/Data/Module.cs
  Epsilon/Epsilon.csproj
  Epsilon/Export/Exporters/ExcelModuleExporter.cs
  Epsilon/Extensions/CoreServiceCollectionExtensions.cs
Labels: enhancement

#21 Fix outcomes being capped at 100
  Epsilon.Canvas.Abstractions/Data/LinkHeader.cs
  Epsilon.Canvas/Response/OutcomeResultResponse.cs
  Epsilon.Canvas/Service/OutcomeService.cs
Labels: bug

#31 Assignments not loading
  Epsilon.Canvas.Abstractions/Model/ModuleItem.cs
  Epsilon.Canvas.Abstractions/Model/ModuleItemType.cs
Labels: bug

#30 Fix exceptions not properly displaying in the console
  Epsilon.Cli/Program.cs
  Epsilon.Cli/Startup.cs
  Epsilon.Cli/appsettings.example.json
Labels: bug

#33 Create code analysis workflow
  .github/workflows/code-analysis.yml
Labels: enhancement

#32 Release v1.0.0-beta3
  .github/workflows/code-analysis.yml
  Epsilon.Canvas.Abstractions/Model/ModuleItem.cs
  Epsilon.Canvas.Abstractions/Model/ModuleItemType.cs
  Epsilon.Cli/Program.cs
  Epsilon.Cli/Startup.cs
  Epsilon.Cli/appsettings.example.json
  Epsilon/Export/ExportOptions.cs
  Epsilon/Extensions/CoreServiceCollectionExtensions.cs
  README.md
Labels: release
